# Custom Language File for Launcher Customizer

[ejs.app]
title = "MFF Launcher"

[ejs.landing]
mediaGitHubURL = ""
mediaXURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = "https://discord.gg/n2hnd5sV8c"

[ejs.settings]
sourceGithubLink = "https://github.com/CopoGamerYT/mff-launcher/"
supportLink = "https://github.com/CopoGamerYT/mff-launcher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenido a MFF Launcher"
welcomeDescription = "Bienvenido a la nueva version de MFF Launcher que agrega nuevas funciones y nuevo gui. Nuevamente si conseguiste este launcher de maneras externas ni te apuntes que hay whitelist jaja, si lo conseguiste en el discord oficial eres bienvenido :D"
welcomeDescCTA = "Dale a continuar."
