[ejs.landing]
updateAvailableTooltip = "Actualización disponible"
usernamePlaceholder = "Nombre de usuario"
usernameEditButton = "Editar"
settingsTooltip = "Configuración"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "DESCONECTADO"
mojangStatus = "ESTADO DE MOJANG"
mojangStatusTooltipTitle = "Servicios"
mojangStatusNETitle = "No esencial"
newsButton = "NOTICIAS"
launchButton = "JUGAR"
launchButtonPlaceholder = "• Ningún servidor seleccionado"
launchDetails = "Por favor espera..."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando noticias..."
newsErrorFailedSpan = "Error al cargar noticias"
newsErrorRetryButton = "Intentar de nuevo"
newsErrorNoneSpan = "Sin noticias"

[ejs.login]
loginCancelText = "Cancelar"
loginSubheader = "INICIO DE SESIÓN DE MINECRAFT"
loginEmailError = "* Valor inválido"
loginEmailPlaceholder = "CORREO ELECTRÓNICO O USUARIO"
loginPasswordError = "* Requerido"
loginPasswordPlaceholder = "CONTRASEÑA"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "¿Olvidaste tu contraseña?"
loginRememberMeText = "¿Recordarme?"
loginButtonText = "INICIAR SESIÓN"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "¿Necesitas una cuenta?"
loginPasswordDisclaimer1 = "Tu contraseña se envía directamente a Mojang y nunca se almacena."
loginPasswordDisclaimer2 = "{appName} no está afiliado con Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Opciones de inicio de sesión"
loginWithMicrosoft = "Iniciar sesión con Microsoft"
loginWithMojang = "Iniciar sesión con Mojang"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Eventos/Series disponibles"
serverSelectConfirm = "Seleccionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Seleccionar una cuenta"
accountSelectConfirm = "Seleccionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configuración"
navAccount = "Cuenta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Lanzador"
navAbout = "Acerca de"
navUpdates = "Actualizaciones"
navDone = "Listo"
tabAccountHeaderText = "Configuración de cuenta"
tabAccountHeaderDesc = "Agrega nuevas cuentas o administra las existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Agregar cuenta de Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Agregar cuenta de Mojang"
minecraftTabHeaderText = "Configuración de Minecraft"
minecraftTabHeaderDesc = "Opciones relacionadas con el lanzamiento del juego."
gameResolutionTitle = "Resolución del juego"
launchFullscreenTitle = "Iniciar en pantalla completa."
autoConnectTitle = "Conectarse automáticamente al servidor al iniciar."
launchDetachedTitle = "Iniciar el juego separado del lanzador."
launchDetachedDesc = "Si el juego no está separado, cerrar el lanzador también cerrará el juego."
tabModsHeaderText = "Configuración de mods"
tabModsHeaderDesc = "Activar o desactivar mods."
switchServerButton = "Cambiar"
requiredMods = "Mods requeridos"
optionalMods = "Mods opcionales"
dropinMods = "Mods integrables"
addMods = "Agregar mods"
dropinRefreshNote = "(F5 para actualizar)"
shaderpacks = "Paquetes de shaders"
shaderpackDesc = "Activa o desactiva shaders. Ten en cuenta que los shaders solo funcionan bien en equipos potentes. Puedes agregar paquetes personalizados aquí."
selectShaderpack = "Seleccionar paquete de sombreado"
tabJavaHeaderText = "Configuración de Java"
tabJavaHeaderDesc = "Administra la configuración de Java (avanzado)."
memoryTitle = "Memoria"
maxRAM = "RAM máxima"
minRAM = "RAM mínima"
memoryDesc = "La RAM mínima recomendada es de 3 GB. Establecer los valores mínimo y máximo iguales puede reducir el lag."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Ejecutable de Java"
javaExecSelDialogTitle = "Seleccionar ejecutable de Java"
javaExecSelButtonText = "Elegir archivo"
javaExecDesc = "El ejecutable de Java se valida antes de iniciar el juego."
javaPathDesc = "La ruta debe terminar con <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opciones adicionales de JVM"
jvmOptsDesc = "Opciones que se proporcionarán a la JVM en tiempo de ejecución. <em>-Xms</em> y <em>-Xmx</em> no deben incluirse."
launcherTabHeaderText = "Configuración del lanzador"
launcherTabHeaderDesc = "Opciones relacionadas con el lanzador."
allowPrereleaseTitle = "Permitir actualizaciones preliminares."
allowPrereleaseDesc = "Las versiones preliminares incluyen nuevas funciones que pueden no estar completamente probadas o integradas.<br>Esto siempre será verdadero si estás usando una versión preliminar."
dataDirectoryTitle = "Directorio de datos"
selectDataDirectory = "Seleccionar directorio de datos"
chooseFolder = "Elegir carpeta"
dataDirectoryDesc = "Todos los archivos del juego y las instalaciones locales de Java se almacenarán en el directorio de datos.<br>Las capturas de pantalla y los mundos guardados se almacenan en la carpeta de instancia correspondiente a la configuración del servidor."
aboutTabHeaderText = "Acerca de"
aboutTabHeaderDesc = "Ver información y notas de la versión actual."
aboutTitle = "{appName}"
stableRelease = "Versión estable"
versionText = "Versión "
sourceGithub = "Fuente (GitHub)"
support = "Soporte"
devToolsConsole = "Consola de herramientas de desarrollo"
releaseNotes = "Notas de la versión"
changelog = "Registro de cambios"
noReleaseNotes = "Sin notas de versión"
viewReleaseNotes = "Ver notas de versión en GitHub"
launcherUpdatesHeaderText = "Actualizaciones del lanzador"
launcherUpdatesHeaderDesc = "Descarga, instala y revisa actualizaciones del lanzador."
checkForUpdates = "Buscar actualizaciones"
whatsNew = "Novedades"
updateReleaseNotes = "Notas de la actualización"


[ejs.waiting]
waitingText = "Esperando a Microsoft..."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.discord]
waiting = "Esperando al cliente..."
state = "Servidor: {shortId}"

[js.index]
microsoftLoginTitle = "Inicio de sesión con Microsoft"
microsoftLogoutTitle = "Cerrar sesión de Microsoft"

[js.login]
login = "INICIAR SESIÓN"
loggingIn = "INICIANDO SESIÓN"
success = "ÉXITO"
tryAgain = "Intentar de nuevo"

[js.login.error]
invalidValue = "* Valor inválido"
requiredValue = "* Requerido"

[js.login.error.unknown]
title = "Error desconocido durante el inicio de sesión"
desc = "Ocurrió un error desconocido. Consulta la consola para más detalles."

[js.landing.launch]
pleaseWait = "Por favor espera..."
failureTitle = "Error al iniciar"
failureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
okay = "Aceptar"

[js.landing.selectedAccount]
noAccountSelected = "Ninguna cuenta seleccionada"

[js.landing.selectedServer]
noSelection = "Ningún servidor seleccionado"
loading = "Cargando..."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFF"
players = "JUGADORES"

[js.landing.systemScan]
checking = "Verificando información del sistema..."
noCompatibleJava = "No se encontró<br>una instalación compatible de Java"
installJavaMessage = "Para iniciar Minecraft, necesitas una instalación de Java {major} de 64 bits. ¿Deseas que instalemos una copia?"
installJava = "Instalar Java"
installJavaManually = "Instalar manualmente"
javaDownloadPrepare = "Preparando descarga de Java..."
javaDownloadFailureTitle = "Error al descargar Java"
javaDownloadFailureText = "Consulta la consola (CTRL + Shift + i) para más detalles."
javaRequired = "Java es requerido<br>para iniciar"
javaRequiredMessage = "Se requiere una instalación válida de Java {major} x64 para iniciar.<br><br>Consulta nuestra <a href=\"https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java\">Guía de gestión de Java</a> para instrucciones."
javaRequiredDismiss = "Entendido"
javaRequiredCancel = "Regresar"

[js.landing.downloadJava]
findJdkFailure = "No se pudo encontrar una distribución de OpenJDK."
javaDownloadCorruptedError = "El JDK descargado tiene un hash incorrecto, el archivo puede estar dañado."
extractingJava = "Extrayendo Java"
javaInstalled = "¡Java instalado!"

[js.landing.dlAsync]
loadingServerInfo = "Cargando información del servidor..."
fatalError = "Error fatal"
unableToLoadDistributionIndex = "No se pudo cargar una copia del índice de distribución. Consulta la consola (CTRL + Shift + i) para más detalles."
pleaseWait = "Por favor espera..."
errorDuringLaunchTitle = "Error al iniciar"
seeConsoleForDetails = "Consulta la consola (CTRL + Shift + i) para más detalles."
validatingFileIntegrity = "Validando integridad de archivos..."
errorDuringFileVerificationTitle = "Error al verificar archivos"
downloadingFiles = "Descargando archivos..."
errorDuringFileDownloadTitle = "Error al descargar archivos"
preparingToLaunch = "Preparando para iniciar..."
launchingGame = "Iniciando juego..."
launchWrapperNotDownloaded = "El archivo principal, LaunchWrapper, no se descargó correctamente. Como resultado, el juego no puede iniciarse.<br><br>Para solucionar esto, desactiva temporalmente tu antivirus y vuelve a iniciar el juego.<br><br>Si tienes tiempo, por favor <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">informa del problema</a> e indícanos qué antivirus usas. Nos pondremos en contacto con ellos."
doneEnjoyServer = "Listo. ¡Disfruta del servidor!"
checkConsoleForDetails = "Consulta la consola (CTRL + Shift + i) para más detalles."

[js.landing.news]
checking = "Buscando noticias"

[js.landing.discord]
loading = "Cargando juego..."
joining = "¡Navegando hacia Westeros!"
joined = "¡Explorando el reino!"

[js.overlay]
dismiss = "Cerrar"

[js.settings.fileSelectors]
executables = "Ejecutables"
allFiles = "Todos los archivos"

[js.settings.mstfLogin]
errorTitle = "Algo salió mal"
errorMessage = "La autenticación de Microsoft falló. Por favor, intenta de nuevo."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Algo salió mal"
errorMessage = "La desconexión de Microsoft falló. Por favor, intenta de nuevo."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Seleccionar cuenta"
selectedButton = "Activa &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Advertencia<br>Esta es tu última cuenta"
lastAccountWarningMessage = "Para usar el lanzador debes estar conectado a al menos una cuenta. Tendrás que iniciar sesión nuevamente después.<br><br>¿Estás seguro de que deseas cerrar sesión?"
confirmButton = "Estoy seguro"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Nombre de usuario"
uuid = "UUID"
selectAccount = "Seleccionar cuenta"
selectedAccount = "Activa ✓"
logout = "Cerrar sesión"

[js.settings.dropinMods]
removeButton = "Eliminar"
deleteFailedTitle = "Error al eliminar<br>mod integrable {fullName}"
deleteFailedMessage = "Asegúrate de que el archivo no esté en uso e intenta de nuevo."
failedToggleTitle = "Error al alternar<br>uno o más mods integrables"
okButton = "Aceptar"

[js.settings.serverListing]
mainServer = "Servidor principal"

[js.settings.java]
selectedJava = "Seleccionado: Java {version} ({vendor})"
invalidSelection = "Selección inválida"
requiresJava = "Requiere Java {major} x64."
availableOptions = "Opciones disponibles para Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Versión preliminar"
stableReleaseTitle = "Versión estable"
releaseNotesFailed = "Error al cargar las notas de la versión."

[js.settings.updates]
newReleaseTitle = "Nueva versión disponible"
newPreReleaseTitle = "Nueva versión preliminar disponible"
downloadingButton = "Descargando..."
downloadButton = "Descargar desde GitHub<span style=\"font-size: 10px;color: gray;text-shadow: none !important;\">Cierra el lanzador y ejecuta el archivo dmg para actualizar.</span>"
latestVersionTitle = "Estás usando la última versión"
checkForUpdatesButton = "Buscar actualizaciones"
checkingForUpdatesButton = "Buscando actualizaciones..."

[js.settings.msftLogin]
errorTitle = "Error al iniciar sesión con Microsoft"
errorMessage = "No pudimos autenticar tu cuenta de Microsoft. Por favor, intenta de nuevo."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Error fatal: No se pudo cargar el índice de distribución"
fatalErrorMessage = "No se pudo establecer conexión con nuestros servidores para descargar el índice de distribución. No hay copias locales disponibles.<br><br>El índice de distribución es un archivo esencial que proporciona la información más reciente del servidor. El lanzador no puede iniciarse sin él. Asegúrate de estar conectado a internet y vuelve a iniciar la aplicación."
closeButton = "Cerrar"

[js.uibinder.validateAccount]
failedMessageTitle = "Error al actualizar el inicio de sesión"
failedMessage = "No se pudo actualizar el inicio de sesión de <strong>{account}</strong>. Por favor, selecciona otra cuenta o inicia sesión nuevamente."
failedMessageSelectAnotherAccount = "No se pudo actualizar el inicio de sesión de <strong>{account}</strong>. Por favor, inicia sesión nuevamente."
loginButton = "Iniciar sesión"
selectAnotherAccountButton = "Seleccionar otra cuenta"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Buscando actualizaciones..."
installNowButton = "Instalar ahora"
checkForUpdatesButton = "Buscar actualizaciones"

[js.auth.microsoft.error]
noProfileTitle = "Error durante el inicio de sesión:<br>Perfil no configurado"
noProfileDesc = "Tu cuenta de Microsoft aún no tiene un perfil de Minecraft configurado. Si compraste el juego recientemente o lo obtuviste mediante Xbox Game Pass, debes configurar tu perfil en <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si aún no has comprado el juego, también puedes hacerlo en <a href=\"https://minecraft.net/\">Minecraft.net</a>."
noXboxAccountTitle = "Error durante el inicio de sesión:<br>No hay cuenta de Xbox"
noXboxAccountDesc = "Tu cuenta de Microsoft no tiene una cuenta de Xbox asociada."
xblBannedTitle = "Error durante el inicio de sesión:<br>Xbox Live no disponible"
xblBannedDesc = "Tu cuenta de Microsoft proviene de un país donde Xbox Live no está disponible o está prohibido."
under18Title = "Error durante el inicio de sesión:<br>Se requiere aprobación parental"
under18Desc = "Las cuentas de usuarios menores de 18 años deben ser añadidas a una familia por un adulto."
unknownTitle = "Error desconocido durante el inicio de sesión"
unknownDesc = "Ocurrió un error desconocido. Consulta la consola para más detalles."

[js.auth.mojang.error]
methodNotAllowedTitle = "Error interno:<br>Método no permitido"
methodNotAllowedDesc = "Método no permitido. Por favor, informa de este error."
notFoundTitle = "Error interno:<br>No encontrado"
notFoundDesc = "No se encontró el punto de autenticación. Por favor, informa de este problema."
accountMigratedTitle = "Error durante el inicio de sesión:<br>Cuenta migrada"
accountMigratedDesc = "Intentaste iniciar sesión con una cuenta migrada. Intenta nuevamente usando el correo electrónico como nombre de usuario."
invalidCredentialsTitle = "Error durante el inicio de sesión:<br>Credenciales inválidas"
invalidCredentialsDesc = "El correo electrónico o la contraseña que ingresaste son incorrectos. Por favor, intenta de nuevo."
tooManyAttemptsTitle = "Error durante el inicio de sesión:<br>Demasiados intentos"
tooManyAttemptsDesc = "Ha habido demasiados intentos de inicio de sesión con esta cuenta recientemente. Por favor, intenta más tarde."
invalidTokenTitle = "Error durante el inicio de sesión:<br>Token inválido"
invalidTokenDesc = "El token de acceso proporcionado no es válido."
tokenHasProfileTitle = "Error durante el inicio de sesión:<br>El token tiene perfil"
tokenHasProfileDesc = "El token de acceso ya tiene un perfil asignado. La selección de perfiles aún no está implementada."
credentialsMissingTitle = "Error durante el inicio de sesión:<br>Faltan credenciales"
credentialsMissingDesc = "No se ingresó el nombre de usuario o la contraseña, o la contraseña tiene menos de 3 caracteres."
invalidSaltVersionTitle = "Error durante el inicio de sesión:<br>Versión de sal inválida"
invalidSaltVersionDesc = "Versión de sal inválida."
unsupportedMediaTypeTitle = "Error interno:<br>Tipo de medio no compatible"
unsupportedMediaTypeDesc = "Tipo de medio no compatible. Por favor, informa de este error."
accountGoneTitle = "Error durante el inicio de sesión:<br>Cuenta migrada"
accountGoneDesc = "La cuenta ha sido migrada a una cuenta de Microsoft. Por favor, inicia sesión con Microsoft."
unreachableTitle = "Error durante el inicio de sesión:<br>Servidor inaccesible"
unreachableDesc = "No se pudo acceder a los servidores de autenticación. Asegúrate de que estén en línea y que tengas conexión a internet."
gameNotPurchasedTitle = "Error durante el inicio de sesión:<br>Juego no comprado"
gameNotPurchasedDesc = "La cuenta con la que intentas iniciar sesión no ha comprado una copia de Minecraft. Puedes adquirir una en <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Error desconocido durante el inicio de sesión"
unknownErrorDesc = "Ocurrió un error desconocido. Consulta la consola para más detalles."

